version: '3.8'

services:
  ubuntu-os:
    build: ./os
    # ports:
      # - 80:80 # physical port : container port
      # - 443:443 # physical port : container port
    volumes:
      - ./os/home:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
    # 必須要加下面這一行保證 ubuntu os 不會自行退出
    # 如果無法正常建立，可能是 Dockerfile 內指令有誤，需手動執行 docker-compose 等指令確認 bug 原因
    tty: true
    environment:
      - DISPLAY
      - XAUTH_ID
    network_mode: host # X11-forwarding 必須為 host mode，與主機共用 network 的命名空間(應該)

volumes:
  homepage:

#networks:
#  test:
#    driver: bridge
